name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to DreamHost
        run: |
          curl -X POST \
            -H "X-Hub-Signature-256: sha256=${{ secrets.DREAMHOST_WEBHOOK_SECRET }}" \
            -d @- \
            ${{ secrets.DREAMHOST_WEBHOOK_URL }} << 'EOF'
          $(cat $GITHUB_EVENT_PATH)
          EOF
      
      - name: Verify deployment
        run: |
          echo "✅ Deployment triggered"
          echo "Check your DreamHost server at: a11yscan.xyz"
